project:
  type: manuscript
  output-dir: docs

title: "My Document"
bibliography: references.bib
csl: apa-6th-edition.csl

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
    code-fold: true
    code-summary: "Show code"
  docx: default
  jats: default

execute:
  freeze: true
